# The Yambar configuration file.

bar:
  height: 40
  location: top
  font: Iosevka:pixelsize=20, Material Symbols Outlined:pixelsize=16
  background: 2B303B80
  foreground: C6D0F5FF
  spacing: 10
  border:
    bottom-width: 3
    color: 64727D80

  left:
    - river:
        anchors:
          - base: &tags
              margin: 10
              conditions:
                id == 1: {string: {text: "1"}}
                id == 2: {string: {text: "2"}}
                id == 3: {string: {text: "3"}}
                id == 4: {string: {text: "4"}}
                id == 5: {string: {text: "5"}}
                id == 6: {string: {text: "6"}}
                id == 7: {string: {text: "7"}}
                id == 8: {string: {text: "8"}}
                id == 9: {string: {text: "9"}}
                id == 10: {string: {text: "0"}}
        content:
          map:
            conditions:
              state == urgent:
                map:
                  <<: *tags
                  deco: {background: {color: E7828480}}
              state == focused:
                map:
                  <<: *tags
                  deco: {background: {color: 949CBB30}}
              state == invisible && occupied:
                map:
                  <<: *tags
                  deco: {background: {color: 51576D50}}

  center:
    - river:
        title: {string: {text: "{title}"}}
        content:
          empty: {}

  right:
    - script:
        path: /home/josh/.config/yambar/scripts/updates.sh
        content:
          map:
            conditions:
              pkg > 0:
                string: {text: "📥{pkg}"}
    - alsa:
        card: default
        mixer: Master
        foreground: 99D1DBFF
        content:
          map:
            conditions:
              muted:
                string: {text: "\uE04F {percent}%"}
              ~muted:
                ramp:
                  tag: percent
                  items:
                    - string: {text: "\uE04E {percent}%"}
                    - string: {text: "\uE04D {percent}%"}
                    - string: {text: "\uE050 {percent}%"}
    - backlight:
        name: intel_backlight
        foreground: E5C890FF
        content:
          string: {text: "\uE518 {percent}%"}
    - battery:
        name: BAT1
        poll-interval: 60000
        foreground: A6D189FF
        content:
          map:
            conditions:
              state == "not charging":
                string: {text: "\uE646 {capacity}%"}
              state == charging:
                ramp:
                  tag: capacity
                  items:
                    - string: {text: "\uE1A3 {capacity}%"}
                    - string: {text: "\uF0A2 {capacity}%"}
                    - string: {text: "\uF0A3 {capacity}%"}
                    - string: {text: "\uF0A4 {capacity}%"}
                    - string: {text: "\uF0A5 {capacity}%"}
                    - string: {text: "\uF0A6 {capacity}%"}
                    - string: {text: "\uF0A7 {capacity}%"}
                    - string: {text: "\uF67D {capacity}%"}
              state == discharging:
                ramp:
                  tag: capacity
                  items:
                    - string: {text: "\uE19C {capacity}%"}
                    - string: {text: "\uEBD9 {capacity}%"}
                    - string: {text: "\uEBE0 {capacity}%"}
                    - string: {text: "\uEBDD {capacity}%"}
                    - string: {text: "\uEBE2 {capacity}%"}
                    - string: {text: "\uEBD4 {capacity}%"}
                    - string: {text: "\uEBD2 {capacity}%"}
                    - string: {text: "\uE1A4 {capacity}%"}
              state == unknown:
                string: {text: "\uE1A6 {capacity}%"}
    - clock:
        time-format: "%H:%M"
        foreground: F4B8E4FF
        content:
          string: {text: "\uE8B5 {time}"}
    - clock:
        date-format: "%a %b %d"
        foreground: 81C8BEFF
        content:
          string: {text: "\uEBCC {date}"}
    - network:
        name: wlan0
        poll-interval: 60000
        foreground: BABBF1FF
        content:
          map:
            right-margin: 10
            conditions:
              state == up:
                string: {text: "\uE63E {ssid}"}
              state == down:
                string: {text: "\uE648 Disconnected"}
